# Generated by Django 5.0.3 on 2024-04-25 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('employee_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='employee_id')),
                ('employee_name', models.CharField(max_length=50)),
                ('leave_type', models.CharField(choices=[('RH', 'Restricted Holiday'), ('CL', 'Casual Leave'), ('EL', 'Earned leave'), ('WFH', 'Work from home')], default='CL', max_length=3)),
                ('app_leave_cl', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('app_leave_el', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('app_leave_rh', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('available_leave_balance_cl', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('available_leave_balance_rh', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('available_leave_balance_el', models.DecimalField(decimal_places=2, default=30.0, max_digits=4)),
                ('has_applied', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hrmsapp_leaveapplication',
            },
        ),
    ]
