# Generated by Django 5.0.3 on 2024-05-15 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Leave_Data',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=255)),
                ('leave_description', models.CharField(max_length=5000)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_days', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_of_request', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'emp_leave_data',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('employee_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='employee_id')),
                ('employee_name', models.CharField(max_length=50)),
                ('leave_type', models.CharField(choices=[('RH', 'Restricted Holiday'), ('CL', 'Casual Leave'), ('EL', 'Earned leave'), ('WFH', 'Work from home')], default='CL', max_length=3)),
                ('app_leave_cl', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('app_leave_el', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('app_leave_rh', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('available_leave_balance_cl', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('available_leave_balance_rh', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('available_leave_balance_el', models.DecimalField(decimal_places=2, default=30.0, max_digits=4)),
                ('has_applied', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hrms_leaveapplication',
            },
        ),
    ]
